services:
  database:
    image: postgres:16
    container_name: database
    environment:
      POSTGRES_USER: sreuser
      POSTGRES_PASSWORD: srepass
      POSTGRES_DB: appdb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d:ro
    networks: [sre_net]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h localhost -p 5432",
        ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  backend:
    build: ./backend
    container_name: backend
    environment:
      DATABASE_URL: postgres://sreuser:srepass@database:5432/appdb?sslmode=disable
    networks: [sre_net]
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: frontend
    networks: [sre_net]
    depends_on: [backend]
    ports:
      - "80:80" # serve static site on host port 80

  kong:
    image: kong:3.6
    container_name: kong
    ports:
      - "8000:8000" # proxy (browser -> Kong)
      - "8443:8443" # proxy TLS optional
      - "8001:8001" # admin (optional)
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_PROXY_LISTEN: 0.0.0.0:8000,0.0.0.0:8443 ssl
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    volumes:
      - ./kong/kong.yml:/etc/kong/kong.yml:ro
    networks: [sre_net]
    depends_on: [backend, frontend]

networks:
  sre_net:

volumes:
  db_data:
